/* Even Fibonacci numbers
Problem 2

Each new term in the Fibonacci sequence is generated by adding the previous two terms.
By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million,
find the sum of the even-valued terms.
*/

#include <stdio.h>
#include <limits.h>

int main()
{
    // results in bytes
    printf("SizeOf(Integer): %d\n", sizeof(int));
    printf("SizeOf(Long): %d\n", sizeof(long));
    printf("SizeOf(unsigned int): %d\n", sizeof(unsigned int));
    return 0;
}

