/* Even Fibonacci numbers
Problem 2

Each new term in the Fibonacci sequence is generated by adding the previous two terms.
By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million,
find the sum of the even-valued terms.
*/

#include <stdio.h>
#include <limits.h>
#define MAX 4000000
// #define MAX 10

int main()
{
    unsigned int n = 0;
    unsigned int a = 0;
    unsigned int b = 1;
    unsigned int sum = 0;
    unsigned int evenSum = 0;

    while (sum <= MAX)
    {
        printf("\n%i: sum= %d\t", n+1, sum = a + b);
        if (!(sum % 2))
        {
            evenSum += sum;
            printf("\n*even sum: %i\n", evenSum);
        }
        a = b;
        // printf("a: %d\t",a);
        b = sum;
        // printf("b: %d\t",b);
        n++;
    }

    printf("\neven sum: %i\n", evenSum);
    return 0;
}

